language: objective-c
osx_image: xcode8.2
xcode_project: BridgeSDK.xcodeproj
xcode_scheme: BridgeSDK
cache:
- bundler
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- gem install bundler
- bundle install
- "./travis/install-mogenerator.sh"
- "./travis/install-appledoc.sh"
script:
- "./travis/build.sh"
deploy:
  provider: s3
  access_key_id: AKIAI6OL6JAPHW5QJTLQ
  secret_access_key:
    secure: ur2qqEudbSmVAtOfAbHbyjM9k05GBCvd9HCN+ujn8adHo2Zoka9pbAFYfP2STFMCBkjyfIqHZTWxbisqvn/ofMmruoO9ve8k0LtxQVn/43EW8DC4feftyBmU6ZMlbgtvfFuG452EazQGhLzmMedBhMT6hrU5D8sbVQsAXqGmEGY=
  bucket: developer.sagebridge.org
  skip_cleanup: true
  local_dir: Documentation
  upload-dir: "$TRAVIS_XCODE_SCHEME/$TRAVIS_TAG"
  on:
    tags: true
